/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class hu_qgears_textrender_stbtt_StbTrueTypeNative */

#ifndef _Included_hu_qgears_textrender_stbtt_StbTrueTypeNative
#define _Included_hu_qgears_textrender_stbtt_StbTrueTypeNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     hu_qgears_textrender_stbtt_StbTrueTypeNative
 * Method:    createSurfaceWithDataPrivate
 * Signature: (Ljava/nio/ByteBuffer;II)I
 */
JNIEXPORT jint JNICALL Java_hu_qgears_textrender_stbtt_StbTrueTypeNative_createSurfaceWithDataPrivate
  (JNIEnv *, jobject, jobject, jint, jint);

/*
 * Class:     hu_qgears_textrender_stbtt_StbTrueTypeNative
 * Method:    renderTextPrivate
 * Signature: (ILjava/lang/String;Ljava/lang/String;Lhu/qgears/images/text/EHorizontalAlign;Lhu/qgears/images/text/EVerticalAlign;IIIIFFFFZLhu/qgears/images/text/EWrapMode;)Lhu/qgears/images/SizeInt;
 */
JNIEXPORT jobject JNICALL Java_hu_qgears_textrender_stbtt_StbTrueTypeNative_renderTextPrivate
  (JNIEnv *, jobject, jint, jstring, jstring, jobject, jobject, jint, jint, jint, jint, jfloat, jfloat, jfloat, jfloat, jboolean, jobject);

/*
 * Class:     hu_qgears_textrender_stbtt_StbTrueTypeNative
 * Method:    layoutTextPrivate
 * Signature: (Ljava/lang/String;Ljava/lang/String;Lhu/qgears/images/text/EHorizontalAlign;Lhu/qgears/images/text/EVerticalAlign;IILhu/qgears/images/text/EWrapMode;)Lhu/qgears/images/SizeInt;
 */
JNIEXPORT jobject JNICALL Java_hu_qgears_textrender_stbtt_StbTrueTypeNative_layoutTextPrivate
  (JNIEnv *, jobject, jstring, jstring, jobject, jobject, jint, jint, jobject);

#ifdef __cplusplus
}
#endif
#endif
