/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class hu_qgears_images_devil_NativeDevIL */

#ifndef _Included_hu_qgears_images_devil_NativeDevIL
#define _Included_hu_qgears_images_devil_NativeDevIL
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     hu_qgears_images_devil_NativeDevIL
 * Method:    initDevIL
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_hu_qgears_images_devil_NativeDevIL_initDevIL
  (JNIEnv *, jobject);

/*
 * Class:     hu_qgears_images_devil_NativeDevIL
 * Method:    bindImage
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_hu_qgears_images_devil_NativeDevIL_bindImage
  (JNIEnv *, jobject);

/*
 * Class:     hu_qgears_images_devil_NativeDevIL
 * Method:    getTypeId
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_hu_qgears_images_devil_NativeDevIL_getTypeId
  (JNIEnv *, jobject, jstring);

/*
 * Class:     hu_qgears_images_devil_NativeDevIL
 * Method:    loadImage
 * Signature: (Ljava/nio/ByteBuffer;I)I
 */
JNIEXPORT jint JNICALL Java_hu_qgears_images_devil_NativeDevIL_loadImage
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     hu_qgears_images_devil_NativeDevIL
 * Method:    convertImage
 * Signature: ()Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_hu_qgears_images_devil_NativeDevIL_convertImage
  (JNIEnv *, jobject);

/*
 * Class:     hu_qgears_images_devil_NativeDevIL
 * Method:    getWidthPrivate
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_hu_qgears_images_devil_NativeDevIL_getWidthPrivate
  (JNIEnv *, jobject);

/*
 * Class:     hu_qgears_images_devil_NativeDevIL
 * Method:    getHeightPrivate
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_hu_qgears_images_devil_NativeDevIL_getHeightPrivate
  (JNIEnv *, jobject);

/*
 * Class:     hu_qgears_images_devil_NativeDevIL
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_hu_qgears_images_devil_NativeDevIL_init
  (JNIEnv *, jobject);

/*
 * Class:     hu_qgears_images_devil_NativeDevIL
 * Method:    saveImage
 * Signature: (Ljava/nio/ByteBuffer;Ljava/lang/String;II)V
 */
JNIEXPORT void JNICALL Java_hu_qgears_images_devil_NativeDevIL_saveImage
  (JNIEnv *, jobject, jobject, jstring, jint, jint);

/*
 * Class:     hu_qgears_images_devil_NativeDevIL
 * Method:    nativeDispose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_hu_qgears_images_devil_NativeDevIL_nativeDispose
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
