/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class hu_qgears_images_tiff_ImageData */

#ifndef _Included_hu_qgears_images_tiff_ImageData
#define _Included_hu_qgears_images_tiff_ImageData
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     hu_qgears_images_tiff_ImageData
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_hu_qgears_images_tiff_ImageData_init
  (JNIEnv *, jobject);

/*
 * Class:     hu_qgears_images_tiff_ImageData
 * Method:    getWidth
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_hu_qgears_images_tiff_ImageData_getWidth
  (JNIEnv *, jobject);

/*
 * Class:     hu_qgears_images_tiff_ImageData
 * Method:    getHeight
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_hu_qgears_images_tiff_ImageData_getHeight
  (JNIEnv *, jobject);

/*
 * Class:     hu_qgears_images_tiff_ImageData
 * Method:    getPixelDataOffset
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_hu_qgears_images_tiff_ImageData_getPixelDataOffset
  (JNIEnv *, jclass);

/*
 * Class:     hu_qgears_images_tiff_ImageData
 * Method:    disposePrimitive
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_hu_qgears_images_tiff_ImageData_disposePrimitive
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
