/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class hu_qgears_images_tiff_NativeTiffLoader */

#ifndef _Included_hu_qgears_images_tiff_NativeTiffLoader
#define _Included_hu_qgears_images_tiff_NativeTiffLoader
#ifdef __cplusplus
extern "C" {
#endif
#undef hu_qgears_images_tiff_NativeTiffLoader_maximumHeaderSize
#define hu_qgears_images_tiff_NativeTiffLoader_maximumHeaderSize 1024L
/*
 * Class:     hu_qgears_images_tiff_NativeTiffLoader
 * Method:    loadTiffImagePrimitive
 * Signature: (Ljava/nio/ByteBuffer;Lhu/qgears/images/tiff/ImageData;)V
 */
JNIEXPORT void JNICALL Java_hu_qgears_images_tiff_NativeTiffLoader_loadTiffImagePrimitive
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     hu_qgears_images_tiff_NativeTiffLoader
 * Method:    saveImageAsTiffPrimitive
 * Signature: (IILjava/nio/ByteBuffer;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_hu_qgears_images_tiff_NativeTiffLoader_saveImageAsTiffPrimitive
  (JNIEnv *, jobject, jint, jint, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
