/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class hu_qgears_textrender_TrueTypeFont */

#ifndef _Included_hu_qgears_textrender_TrueTypeFont
#define _Included_hu_qgears_textrender_TrueTypeFont
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     hu_qgears_textrender_TrueTypeFont
 * Method:    nativeDispose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_hu_qgears_textrender_TrueTypeFont_nativeDispose
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
