/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class hu_qgears_textrender_libschrift_LibschriftNative */

#ifndef _Included_hu_qgears_textrender_libschrift_LibschriftNative
#define _Included_hu_qgears_textrender_libschrift_LibschriftNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     hu_qgears_textrender_libschrift_LibschriftNative
 * Method:    createSurfaceWithDataPrivate
 * Signature: (Ljava/nio/ByteBuffer;II)J
 */
JNIEXPORT jlong JNICALL Java_hu_qgears_textrender_libschrift_LibschriftNative_createSurfaceWithDataPrivate
  (JNIEnv *, jobject, jobject, jint, jint);

/*
 * Class:     hu_qgears_textrender_libschrift_LibschriftNative
 * Method:    renderTextPrivate
 * Signature: (JLjava/lang/String;Ljava/lang/String;Lhu/qgears/images/text/EHorizontalAlign;Lhu/qgears/images/text/EVerticalAlign;IIIIFFFFZLhu/qgears/images/text/EWrapMode;)Lhu/qgears/images/SizeInt;
 */
JNIEXPORT jobject JNICALL Java_hu_qgears_textrender_libschrift_LibschriftNative_renderTextPrivate
  (JNIEnv *, jobject, jlong, jstring, jstring, jobject, jobject, jint, jint, jint, jint, jfloat, jfloat, jfloat, jfloat, jboolean, jobject);

/*
 * Class:     hu_qgears_textrender_libschrift_LibschriftNative
 * Method:    layoutTextPrivate
 * Signature: (Ljava/lang/String;Ljava/lang/String;Lhu/qgears/images/text/EHorizontalAlign;Lhu/qgears/images/text/EVerticalAlign;IILhu/qgears/images/text/EWrapMode;)Lhu/qgears/images/SizeInt;
 */
JNIEXPORT jobject JNICALL Java_hu_qgears_textrender_libschrift_LibschriftNative_layoutTextPrivate
  (JNIEnv *, jobject, jstring, jstring, jobject, jobject, jint, jint, jobject);

/*
 * Class:     hu_qgears_textrender_libschrift_LibschriftNative
 * Method:    disposeSurfacePrivate
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_hu_qgears_textrender_libschrift_LibschriftNative_disposeSurfacePrivate
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
