= Command line tools

Selection of command line tools.

== git-backup

Back up git repositiories using git itself:

 * Clone remote repositories by hand into a folder
 * Run git-backup on the backup folder:
    * Iterates all git clones
    * git fetch (all new objects and update all remote refs)
    * Tag all current tags and branches.
    * The backups tags are not going to match any new tags in the server so they will not be overwritten.
    * The backup tag names contain a salt so a remote attacker can not delete these tags (until he knows the salt)
    
Return value: Returns non 0 in case any of the gits could not be fetched or the log could not be uploaded.

Logging:

 * If backupLogFile is specified: then the result log is pushed into a git repository (in which the log file resides).
 * If backupLogFile is not specified: Logs are written to stdout
  
Proposed configuration is to start backup by timer (eg. daily) and restart the process (eg. every hour) in case the of non 0 return value.


== git2zip

Get all files from a git repsitory state (branch or tag) and zip them into a single file. Features:

 * Works on a bare repository (eg. server side repo)
 * Possible to zip a subfolder only
 * Possible to add folder prefix
 * Created zip file is binary reproducible when the same tag is used (timestamps are set to epoch)
 * Uses JGit to access the repo

== srvBackup

Iterate all files within a folder which are not under gitignore. Collects all paths and creates a file (shell script)
that stores the file modes (RWX, User, group, others).

This tool can be used to back up /etc on a server using git (a clone of this feature of etckeeper).