/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class hu_qgears_sdlwindow_SdlWindowNative */

#ifndef _Included_hu_qgears_sdlwindow_SdlWindowNative
#define _Included_hu_qgears_sdlwindow_SdlWindowNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     hu_qgears_sdlwindow_SdlWindowNative
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_hu_qgears_sdlwindow_SdlWindowNative_init
  (JNIEnv *, jobject);

/*
 * Class:     hu_qgears_sdlwindow_SdlWindowNative
 * Method:    openWindow
 * Signature: (IILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_hu_qgears_sdlwindow_SdlWindowNative_openWindow
  (JNIEnv *, jobject, jint, jint, jstring);

/*
 * Class:     hu_qgears_sdlwindow_SdlWindowNative
 * Method:    drawExample
 * Signature: (Ljava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_hu_qgears_sdlwindow_SdlWindowNative_drawExample
  (JNIEnv *, jobject, jobject);

/*
 * Class:     hu_qgears_sdlwindow_SdlWindowNative
 * Method:    updateFrame
 * Signature: (Ljava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_hu_qgears_sdlwindow_SdlWindowNative_updateFrame
  (JNIEnv *, jobject, jobject);

/*
 * Class:     hu_qgears_sdlwindow_SdlWindowNative
 * Method:    closeWindow
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_hu_qgears_sdlwindow_SdlWindowNative_closeWindow
  (JNIEnv *, jobject);

/*
 * Class:     hu_qgears_sdlwindow_SdlWindowNative
 * Method:    processEvents
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_hu_qgears_sdlwindow_SdlWindowNative_processEvents
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
