/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class hu_qgears_shm_SharedMemoryNative */

#ifndef _Included_hu_qgears_shm_SharedMemoryNative
#define _Included_hu_qgears_shm_SharedMemoryNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     hu_qgears_shm_SharedMemoryNative
 * Method:    init2
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_hu_qgears_shm_SharedMemoryNative_init2
  (JNIEnv *, jobject, jlong);

/*
 * Class:     hu_qgears_shm_SharedMemoryNative
 * Method:    init
 * Signature: (Ljava/lang/String;IJ)V
 */
JNIEXPORT void JNICALL Java_hu_qgears_shm_SharedMemoryNative_init
  (JNIEnv *, jobject, jstring, jint, jlong);

/*
 * Class:     hu_qgears_shm_SharedMemoryNative
 * Method:    initFile
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_hu_qgears_shm_SharedMemoryNative_initFile
  (JNIEnv *, jobject, jstring);

/*
 * Class:     hu_qgears_shm_SharedMemoryNative
 * Method:    sync
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_hu_qgears_shm_SharedMemoryNative_sync
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     hu_qgears_shm_SharedMemoryNative
 * Method:    nativeDispose
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_hu_qgears_shm_SharedMemoryNative_nativeDispose
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     hu_qgears_shm_SharedMemoryNative
 * Method:    getSize
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_hu_qgears_shm_SharedMemoryNative_getSize
  (JNIEnv *, jobject);

/*
 * Class:     hu_qgears_shm_SharedMemoryNative
 * Method:    getAccessor
 * Signature: ()Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_hu_qgears_shm_SharedMemoryNative_getAccessor
  (JNIEnv *, jobject);

/*
 * Class:     hu_qgears_shm_SharedMemoryNative
 * Method:    getNativePointer1
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_hu_qgears_shm_SharedMemoryNative_getNativePointer1
  (JNIEnv *, jobject);

/*
 * Class:     hu_qgears_shm_SharedMemoryNative
 * Method:    getNativePointer2
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_hu_qgears_shm_SharedMemoryNative_getNativePointer2
  (JNIEnv *, jobject);

/*
 * Class:     hu_qgears_shm_SharedMemoryNative
 * Method:    deleteSharedMemoryById
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_hu_qgears_shm_SharedMemoryNative_deleteSharedMemoryById
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
