/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class hu_qgears_shm_dlmalloc_DlMallocPoolNative */

#ifndef _Included_hu_qgears_shm_dlmalloc_DlMallocPoolNative
#define _Included_hu_qgears_shm_dlmalloc_DlMallocPoolNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     hu_qgears_shm_dlmalloc_DlMallocPoolNative
 * Method:    init
 * Signature: (Ljava/nio/ByteBuffer;JZ)V
 */
JNIEXPORT void JNICALL Java_hu_qgears_shm_dlmalloc_DlMallocPoolNative_init
  (JNIEnv *, jobject, jobject, jlong, jboolean);

/*
 * Class:     hu_qgears_shm_dlmalloc_DlMallocPoolNative
 * Method:    dlalloc
 * Signature: (JI)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_hu_qgears_shm_dlmalloc_DlMallocPoolNative_dlalloc
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     hu_qgears_shm_dlmalloc_DlMallocPoolNative
 * Method:    dlfree
 * Signature: (Ljava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_hu_qgears_shm_dlmalloc_DlMallocPoolNative_dlfree
  (JNIEnv *, jobject, jobject);

/*
 * Class:     hu_qgears_shm_dlmalloc_DlMallocPoolNative
 * Method:    getRelativeAddress
 * Signature: (Ljava/nio/ByteBuffer;)J
 */
JNIEXPORT jlong JNICALL Java_hu_qgears_shm_dlmalloc_DlMallocPoolNative_getRelativeAddress
  (JNIEnv *, jobject, jobject);

/*
 * Class:     hu_qgears_shm_dlmalloc_DlMallocPoolNative
 * Method:    getNativePointer
 * Signature: (Ljava/nio/ByteBuffer;I)J
 */
JNIEXPORT jlong JNICALL Java_hu_qgears_shm_dlmalloc_DlMallocPoolNative_getNativePointer
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     hu_qgears_shm_dlmalloc_DlMallocPoolNative
 * Method:    nativeDispose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_hu_qgears_shm_dlmalloc_DlMallocPoolNative_nativeDispose
  (JNIEnv *, jobject);

/*
 * Class:     hu_qgears_shm_dlmalloc_DlMallocPoolNative
 * Method:    getAllocatedSize
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_hu_qgears_shm_dlmalloc_DlMallocPoolNative_getAllocatedSize
  (JNIEnv *, jobject);

/*
 * Class:     hu_qgears_shm_dlmalloc_DlMallocPoolNative
 * Method:    getMaxAllocated
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_hu_qgears_shm_dlmalloc_DlMallocPoolNative_getMaxAllocated
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
