/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class hu_qgears_shm_sem_SemaphoreNative */

#ifndef _Included_hu_qgears_shm_sem_SemaphoreNative
#define _Included_hu_qgears_shm_sem_SemaphoreNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     hu_qgears_shm_sem_SemaphoreNative
 * Method:    init
 * Signature: (Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_hu_qgears_shm_sem_SemaphoreNative_init
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     hu_qgears_shm_sem_SemaphoreNative
 * Method:    nativeDispose
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_hu_qgears_shm_sem_SemaphoreNative_nativeDispose
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     hu_qgears_shm_sem_SemaphoreNative
 * Method:    getValue
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_hu_qgears_shm_sem_SemaphoreNative_getValue
  (JNIEnv *, jobject);

/*
 * Class:     hu_qgears_shm_sem_SemaphoreNative
 * Method:    incrementValue
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_hu_qgears_shm_sem_SemaphoreNative_incrementValue
  (JNIEnv *, jobject);

/*
 * Class:     hu_qgears_shm_sem_SemaphoreNative
 * Method:    decrementValue
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_hu_qgears_shm_sem_SemaphoreNative_decrementValue
  (JNIEnv *, jobject);

/*
 * Class:     hu_qgears_shm_sem_SemaphoreNative
 * Method:    decrementValueTry
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_hu_qgears_shm_sem_SemaphoreNative_decrementValueTry
  (JNIEnv *, jobject);

/*
 * Class:     hu_qgears_shm_sem_SemaphoreNative
 * Method:    decrementValueTimed
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_hu_qgears_shm_sem_SemaphoreNative_decrementValueTimed
  (JNIEnv *, jobject, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
