/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class hu_qgears_shm_part_PartNativeMemoryNative */

#ifndef _Included_hu_qgears_shm_part_PartNativeMemoryNative
#define _Included_hu_qgears_shm_part_PartNativeMemoryNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     hu_qgears_shm_part_PartNativeMemoryNative
 * Method:    getByteBuffer
 * Signature: (Ljava/nio/ByteBuffer;JJ)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_hu_qgears_shm_part_PartNativeMemoryNative_getByteBuffer
  (JNIEnv *, jobject, jobject, jlong, jlong);

/*
 * Class:     hu_qgears_shm_part_PartNativeMemoryNative
 * Method:    getNativePointer
 * Signature: (Ljava/nio/ByteBuffer;I)J
 */
JNIEXPORT jlong JNICALL Java_hu_qgears_shm_part_PartNativeMemoryNative_getNativePointer
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     hu_qgears_shm_part_PartNativeMemoryNative
 * Method:    getBuffer
 * Signature: (JJJ)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_hu_qgears_shm_part_PartNativeMemoryNative_getBuffer
  (JNIEnv *, jobject, jlong, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
