/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class hu_qgears_images_libpng_NativeLibPngConnector */

#ifndef _Included_hu_qgears_images_libpng_NativeLibPngConnector
#define _Included_hu_qgears_images_libpng_NativeLibPngConnector
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     hu_qgears_images_libpng_NativeLibPngConnector
 * Method:    getNumberOfChannels
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_hu_qgears_images_libpng_NativeLibPngConnector_getNumberOfChannels
  (JNIEnv *, jobject);

/*
 * Class:     hu_qgears_images_libpng_NativeLibPngConnector
 * Method:    loadImage
 * Signature: (Ljava/nio/ByteBuffer;I)V
 */
JNIEXPORT void JNICALL Java_hu_qgears_images_libpng_NativeLibPngConnector_loadImage
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     hu_qgears_images_libpng_NativeLibPngConnector
 * Method:    closeLoad
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_hu_qgears_images_libpng_NativeLibPngConnector_closeLoad
  (JNIEnv *, jobject);

/*
 * Class:     hu_qgears_images_libpng_NativeLibPngConnector
 * Method:    beginLoad
 * Signature: (Ljava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_hu_qgears_images_libpng_NativeLibPngConnector_beginLoad
  (JNIEnv *, jobject, jobject);

/*
 * Class:     hu_qgears_images_libpng_NativeLibPngConnector
 * Method:    getHeight
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_hu_qgears_images_libpng_NativeLibPngConnector_getHeight
  (JNIEnv *, jobject);

/*
 * Class:     hu_qgears_images_libpng_NativeLibPngConnector
 * Method:    getWidth
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_hu_qgears_images_libpng_NativeLibPngConnector_getWidth
  (JNIEnv *, jobject);

/*
 * Class:     hu_qgears_images_libpng_NativeLibPngConnector
 * Method:    getRowBytes
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_hu_qgears_images_libpng_NativeLibPngConnector_getRowBytes
  (JNIEnv *, jobject);

/*
 * Class:     hu_qgears_images_libpng_NativeLibPngConnector
 * Method:    beginSave
 * Signature: (IIIIZZZLjava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_hu_qgears_images_libpng_NativeLibPngConnector_beginSave
  (JNIEnv *, jobject, jint, jint, jint, jint, jboolean, jboolean, jboolean, jobject);

/*
 * Class:     hu_qgears_images_libpng_NativeLibPngConnector
 * Method:    getFileSize
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_hu_qgears_images_libpng_NativeLibPngConnector_getFileSize
  (JNIEnv *, jobject);

/*
 * Class:     hu_qgears_images_libpng_NativeLibPngConnector
 * Method:    saveImage
 * Signature: (Ljava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_hu_qgears_images_libpng_NativeLibPngConnector_saveImage
  (JNIEnv *, jobject, jobject);

/*
 * Class:     hu_qgears_images_libpng_NativeLibPngConnector
 * Method:    closeSave
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_hu_qgears_images_libpng_NativeLibPngConnector_closeSave
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
